Repository technojam/TechnoJam-App, pull requests merged in 2020-10, with the labels that each got.

#5 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Hacktoberfest, feature, good first issue

#8 Fixes #2 : Created Readme.md
  README.md
Labels: Hacktoberfest, documentation, good first issue

#7 Fix #6 : Creation of PR Template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Hacktoberfest, feature, hacktoberfest-accepted

#13 Fix #12 : Addition of Dependencies for MVVM.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sarthak/technojam/MainActivity.kt
  app/src/main/java/com/sarthak/technojam/ui/splashscreen/SpashScreenViewModel.kt
  app/src/main/java/com/sarthak/technojam/ui/splashscreen/SplashScreenActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
Labels: Hacktoberfest, feature, hacktoberfest-accepted
